### ISSUE TITLE
django-neue-transmeta package is no longer accessible on PyPI

### ISSUE THREAD

**Issue by VojtechMyslivec** [bioinformaticsua/django-neue-transmeta#1]
- https://pypi.org/project/django-neue-transmeta/ returns 404
- `pip` returns `Could not find any downloads that satisfy the requirement django-neue-transmeta`

Is it possible to push the package onto PyPI again?

Thanks

**Comment by joaorafaelalmeida** [comment]
We are not the creators of this repository. However, since we didn't find the original repository, we create this to make the necessary adjustments in the code to work in the Django version > 1.8 for our project.
If you want to install this, we can do it by installing directly from GitHub.
Command: `pip install -e git://github.com/bioinformaticsua/django-neue-transmeta#egg=django-neue-transmeta`
